[workspace]
authors = ["Gary Steele <g.a.steele@tudelft.nl>"]
channels = ["conda-forge"]
name = "FYPLC new"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
jupyterlab = "jupyter lab"
notebook = "jupyter notebook"
myst = "myst start"
execute = "myst execute"
build = { cmd = "myst build", depends_on = ["execute"] }

[dependencies]
jupyterlab = ">=4.6.3,<5"
mystmd = ">=1.10.1,<2"
numpy = ">=2.5.2,<3"
matplotlib = ">=3.11.1,<4"
scipy = ">=1.18.0,<2"
ipywidgets = ">=8.1.9,<9"
pandas = ">=3.0.5,<4"
jupytext = ">=1.19.5,<2"
notebook = ">=7.6"
scikit-learn = ">=1.9.1,<2"
opencv = ">=5.0.0,<6"

[pypi-dependencies]
jupyterlab-myst = ">=2.7.0, <3"
schemdraw = ">=0.23"
helper-functions = ">=2.0.11, <3"
